Repository ISIS3510-G12/Dart-G12, pull requests merged in 2025-04, with the labels that each got.

#23 Feature/posthog analytics
  android/app/src/main/AndroidManifest.xml
  ios/Runner/Info.plist
  lib/data/services/analytics_service.dart
  lib/main.dart
  macos/Runner/Info.plist
  pubspec.lock
  pubspec.yaml
  web/index.html
Labels: feature

#24 trabajen
  assets/images/profile.jpg
  lib/data/repositories/home_repository.dart
  lib/presentation/view_models/profile_view_model.dart
  lib/presentation/views/home_screen.dart
  lib/presentation/views/profile_page.dart
  lib/presentation/widgets/category_icon.dart
Labels: feature, UI/UX

#27 Feature/app events visualization #20
  lib/data/repositories/event_repository.dart
  lib/data/services/analytics_service.dart
  lib/presentation/view_models/event_view_model.dart
  lib/presentation/views/home_screen.dart
  lib/presentation/views/see_all_events_page.dart
  lib/presentation/views/see_all_screen.dart
  lib/presentation/widgets/card.dart
  lib/presentation/widgets/card_event.dart
Labels: feature

#28 Feature/local storage #21
  lib/presentation/view_models/card_view_model.dart
  lib/presentation/view_models/home_view_model.dart
  lib/presentation/views/home_screen.dart
  lib/presentation/widgets/card.dart
  lib/presentation/widgets/place_card.dart
  macos/Flutter/GeneratedPluginRegistrant.swift
  pubspec.lock
  pubspec.yaml
Labels: feature

#29 Refactor event and location repositories to use 'event_id' and 'locat…
  lib/data/repositories/event_repository.dart
  lib/data/repositories/location_repository.dart
  lib/presentation/view_models/see_all_view_model.dart
  lib/presentation/views/home_screen.dart
  lib/presentation/views/see_all_events_page.dart
  lib/presentation/views/see_all_screen.dart
  lib/presentation/widgets/card.dart
  lib/presentation/widgets/category_list.dart
  lib/presentation/widgets/place_card.dart
  lib/presentation/widgets/section_header.dart
Labels: feature, UI/UX

#30 Feature/multithreading support #23
  lib/data/repositories/home_repository.dart
  lib/data/repositories/map_repository.dart
  lib/data/services/local_storage_service.dart
  lib/presentation/view_models/home_view_model.dart
  lib/presentation/views/home_screen.dart
  lib/presentation/widgets/section_header.dart
Labels: feature

#31 Feature/correccion cards #22
  lib/presentation/view_models/card_detail_view_model.dart
  lib/presentation/views/detail_card.dart
Labels: feature, UI/UX

#32 Feature/filter name feature #24
  lib/presentation/view_models/see_all_view_model.dart
  lib/presentation/views/see_all_screen.dart
Labels: feature

#33 Refactor location fetching: improve caching logic and initialization …
  lib/data/repositories/location_repository.dart
  lib/data/repositories/map_repository.dart
  lib/main.dart
  lib/presentation/views/map_page.dart
Labels: feature

#34 Featura/see all storage and threading #24
  lib/data/repositories/event_repository.dart
  lib/data/repositories/location_repository.dart
  lib/presentation/view_models/card_detail_view_model.dart
Labels: feature

#35 Feature/notifications #25
  lib/presentation/view_models/notification_view_model.dart
  lib/presentation/views/Pagina2.dart
  lib/presentation/views/main_screen.dart
  lib/presentation/views/notificacion_page.dart
  lib/presentation/widgets/notification_card.dart
  pubspec.lock
  pubspec.yaml
Labels: feature

#36 DIOSMATAMEPORFAVOR
  lib/data/repositories/access_repository.dart
  lib/data/repositories/auditoriums_repository.dart
  lib/data/repositories/departments_repository.dart
  lib/data/repositories/faculties_repository.dart
  lib/data/repositories/home_repository.dart
  lib/data/repositories/laboratories_repository.dart
  lib/data/repositories/libraries_repository.dart
  lib/data/repositories/location_repository.dart
  lib/data/repositories/services_repository.dart
  lib/data/repositories/sports_facilities.dart
  lib/presentation/view_models/card_detail_view_model.dart
  lib/presentation/view_models/home_view_model.dart
  lib/presentation/view_models/see_all_view_model.dart
  lib/presentation/views/detail_card.dart
  lib/presentation/views/home_screen.dart
  lib/presentation/views/see_all_screen.dart
  lib/presentation/widgets/place_card.dart
Labels: feature, UI/UX

#37 Fix/map view
  lib/data/repositories/map_repository.dart
  lib/presentation/view_models/map_view_model.dart
  lib/presentation/widgets/steps_card.dart
Labels: bug

#38 Feature/access implementation #28
  lib/data/repositories/access_repository.dart
  lib/data/repositories/home_repository.dart
  lib/presentation/view_models/card_detail_view_model.dart
  lib/presentation/view_models/home_view_model.dart
  lib/presentation/view_models/see_all_view_model.dart
  lib/presentation/views/detail_card.dart
  lib/presentation/views/home_screen.dart
  lib/presentation/views/see_all_screen.dart
Labels: feature, UI/UX

#40 Fix/notification view #30
  lib/data/repositories/event_repository.dart
  lib/data/repositories/favorite_repository.dart
  lib/presentation/view_models/card_detail_view_model.dart
  lib/presentation/view_models/notification_view_model.dart
  lib/presentation/views/detail_card.dart
  lib/presentation/views/notificacion_page.dart
  lib/presentation/views/see_all_screen.dart
  lib/presentation/widgets/category_list.dart
  lib/presentation/widgets/notification_card.dart
Labels: feature

#41 Refactor UI components: adjust spacing in HomeScreen, enhance Categor…
  lib/presentation/views/home_screen.dart
  lib/presentation/widgets/category_icon.dart
  lib/presentation/widgets/ovals_painter.dart
  lib/presentation/widgets/section_header.dart
  lib/presentation/widgets/transparent_ovals_painter.dart
Labels: feature, UI/UX

#42 Add favorite functionality to SeeAllViewModel and update related views
  lib/presentation/view_models/see_all_view_model.dart
  lib/presentation/views/detail_card.dart
  lib/presentation/views/main_screen.dart
  lib/presentation/views/see_all_screen.dart
Labels: feature

#45 Implement auditorium functionality: add repository methods, view mode…
  lib/data/repositories/access_repository.dart
  lib/data/repositories/auditoriums_repository.dart
  lib/data/repositories/event_repository.dart
  lib/data/repositories/laboratories_repository.dart
  lib/data/repositories/location_repository.dart
  lib/presentation/view_models/card_detail_view_model.dart
  lib/presentation/view_models/see_all_view_model.dart
  lib/presentation/views/detail_card.dart
  lib/presentation/views/see_all_screen.dart
  lib/presentation/widgets/category_list.dart
Labels: feature

#47 Enhance library functionality: integrate library repository, update v…
  lib/data/repositories/home_repository.dart
  lib/data/repositories/libraries_repository.dart
  lib/presentation/view_models/card_detail_view_model.dart
  lib/presentation/view_models/see_all_view_model.dart
  lib/presentation/views/detail_card.dart
  lib/presentation/views/see_all_screen.dart
  lib/presentation/widgets/category_icon.dart
  lib/presentation/widgets/category_list.dart
Labels: feature

#48 Feature/multithreading repositories #37
  lib/data/repositories/access_repository.dart
  lib/data/repositories/auditoriums_repository.dart
  lib/data/repositories/home_repository.dart
  lib/data/repositories/laboratories_repository.dart
  lib/data/repositories/location_repository.dart
  lib/data/repositories/map_repository.dart
  lib/presentation/view_models/home_view_model.dart
  lib/presentation/view_models/notification_view_model.dart
  lib/presentation/views/detail_card.dart
  lib/presentation/views/home_screen.dart
  lib/presentation/views/notificacion_page.dart
  lib/presentation/widgets/notification_card.dart
Labels: feature

#49 Feature/profile view #35
  lib/presentation/view_models/edit_profile_view_model.dart
  lib/presentation/view_models/profile_view_model.dart
  lib/presentation/views/edit_profile.dart
  lib/presentation/views/profile_page.dart
Labels: feature

#50 Update HomeRepository and UI components: modify Supabase queries, enh…
  lib/data/repositories/home_repository.dart
  lib/presentation/views/home_screen.dart
  lib/presentation/widgets/category_icon.dart
  lib/presentation/widgets/section_header.dart
Labels: feature, UI/UX

#51 Enhance data fetching and UI for events and auditoriums:
  lib/data/repositories/auditoriums_repository.dart
  lib/data/repositories/event_repository.dart
  lib/data/repositories/home_repository.dart
  lib/presentation/view_models/home_view_model.dart
  lib/presentation/views/detail_card.dart
  lib/presentation/views/home_screen.dart
  pubspec.lock
  pubspec.yaml
Labels: feature, UI/UX
